### ISSUE TITLE
invalid sub_pay_channel

### ISSUE THREAD

**Issue by NaMLiM** [aditamagf/check-ign#2]
everytime i use the api, the response from the server is invalid sub_pay_channel. did they change something that broke this library?

**Comment by NaMLiM** [comment]
changing the 'gvtId' value from 19 to 460 fix the problem. i dont know what gvtId mean here

**Comment by aditamagf** [comment]
Fixed in [v1.1](https://github.com/aditamagf/check-ign/releases)
